### ISSUE TITLE
[Into to iOS] Project 1 - Review my app

### ISSUE THREAD

**Issue by gilbox** [gilbox/ios-tip-calculator#1]
The basic version of my app is complete. 
I will be adding improvements and features as time permits. /cc @codepathreview

**Comment by gilbox** [comment]
Added feature: Tipping Game (click the `¯\_(ツ)_/¯` button) /cc @codepathreview

**Comment by gilbox** [comment]
added animations https://github.com/gilbox/ios-tip-calculator/commit/b2b04c98118628840e5d8b947e7734104a6ce1e8
/cc @codepathreview

**Comment by nesquena** [comment]
Gil,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical iOS development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a few extension tasks as well. The extension tasks available on each project are often the most valuable learnings since they dive deeper into common real-world iOS use cases.

Your application will be passed along to the organizers for final admissions. You should hear back again soon. I'd encourage you to continue working on app extensions in the meantime. Let me know if you have any questions.
